coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "tests/**/*"
  - "testdata/**/*"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
